services:
  nginx:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ../nginx-proxy-manager/data:/data
#      - ./data:/data
      - ../nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  redis:
    image: redis:alpine
    container_name: redis_cache
    expose:
      - "6379"
    volumes:
      - ../redis_data:/data

  django-yolo-streaming:
      build:
        dockerfile: Dockerfile
      image: 'django-yolo-streaming:latest'
      container_name: 'django-yolo-streaming'
      restart: unless-stopped
      ports:
        - "8000:8000"
      depends_on:
        redis:
          condition: service_started
        mongodb:
          condition: service_started
      deploy:
        resources:
            reservations:
              devices:
                  - driver: nvidia
                    device_ids: [ all ]
                    capabilities: [ gpu, compute, utility ]
#      command:  python manage.py runserver 0.0.0.0:8000
#      command:  gunicorn --bind 0.0.0.0:8000 stream.wsgi:application

#  asgi-server:
#    build:
#      dockerfile: Dockerfile
#    image: 'django-yolo-streaming:latest'
#    container_name: 'asgi-server'
#    restart: unless-stopped
#    ports:
#      - "8001:8001"
#    depends_on:
#      django-yolo-streaming:
#       condition: service_started
#    command: daphne stream.asgi:application -b 0.0.0.0 -p 8001

  mongodb:
      image: mongo:6-jammy
      container_name: 'mongodb'
      restart: unless-stopped
      ports:
          - '27017:27017'
      volumes:
          - ../mongodb/dbdata6:/data/db