# Generated by Django 5.2.2 on 2025-06-06 01:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionModel',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('IntersectionName', models.CharField(default='', max_length=100, unique=True)),
                ('IntersectionAddress', models.CharField(default='', max_length=100, unique=True)),
                ('IntersectionCountry', models.CharField(default='', max_length=100)),
                ('IntersectionCity', models.CharField(default='', max_length=100)),
                ('coordXY', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('entriesNumber', models.IntegerField()),
                ('individualToggle', models.BooleanField(default=False)),
                ('IntersectionIsSmartAlgorithmEnabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FullName', models.CharField(default='', max_length=100)),
                ('City', models.CharField(default='', max_length=100)),
                ('Country', models.CharField(default='', max_length=100)),
                ('County/State', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IntersectionEntryModel',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('entry_number', models.PositiveIntegerField()),
                ('coordinates1', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coordinates2', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('traffic_score', models.IntegerField()),
                ('intersectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='webcam.intersectionmodel')),
            ],
        ),
    ]
