# Generated by Django 5.2.2 on 2025-06-06 20:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionModel',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('address', models.CharField(default='', max_length=100, unique=True)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('entries_number', models.IntegerField(null=True)),
                ('individual_toggle', models.BooleanField(default=False)),
                ('enabled_smart_algorithm', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('county_or_state', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IntersectionEntryModel',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('entry_number', models.PositiveIntegerField(null=True)),
                ('coordinates1', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('coordinates2', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('traffic_score', models.IntegerField(default=0)),
                ('intersection_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webcam.intersectionmodel')),
            ],
        ),
    ]
