# Generated by Django 5.2.2 on 2025-06-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intersectionmodel',
            name='enabled_smart_algorithm',
        ),
        migrations.AddField(
            model_name='intersectionmodel',
            name='smart_algorithm_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
