# Generated by Django 5.2.3 on 2025-06-10 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_remove_intersectionmodel_enabled_smart_algorithm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intersectionentrymodel',
            name='intersection_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='webcam.intersectionmodel'),
        ),
    ]
