# Generated by Django 5.2.3 on 2025-06-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0004_remove_intersectionentrymodel_intersection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgVehicleThroughputDataPointModel',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('intersection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_vehicle_throughput_data', to='webcam.intersectionmodel')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['intersection', 'timestamp'], name='webcam_avgv_interse_52e2e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvgWaitingTimeDataPointModel',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('intersection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_waiting_time_data', to='webcam.intersectionmodel')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['intersection', 'timestamp'], name='webcam_avgw_interse_0b9f74_idx')],
            },
        ),
    ]
